##
## EPITECH PROJECT, 2019
## oui
## File description:
## oui
##

SRC	=	main.c		\

NAME	=	menger

all:	$(NAME)

$(NAME):	$(OBJ)
	gcc $(SRC) -o $(NAME)

clean:
	rm -f *~
	rm -f *#
	rm -f *.o

fclean: clean
	rm -f $(NAME)

re: fclean all

