##
## EPITECH PROJECT, 2019
## ouioui
## File description:
## oui
##

all: $(OBJ)
	make -C ./lib_ncurses
	make -C ./lib_sfml

clean:
	make clean -C ./lib_ncurses
	make clean -C ./lib_sfml

fclean: clean
	make fclean -C ./lib_ncurses
	make fclean -C ./lib_sfml

re: fclean all


